export const URL = {
  AUTH: {
    SIGN_UP: 'auth/sign-up',
    SING_IN: 'auth/sign-in',
    GET_ROLES: 'auth/get-roles',
    GET_CURRENT_USER: '',
    LOGOUT: '',
    REFRESH_TOKEN: '',
    FORGOT_PASSWORD: '',
    RESET_PASSWORD: '',
    UPDATE_ROLE_GROUP: 'auth/update-rolegroup',
    GET_ROLE_GROUPS: 'auth/get-rolegroups',
  },
  CUSTOMER: {
    GETALL: 'customer',
    GETONE: 'customer',
    CREATE: 'customer',
    UPDATE: 'customer',
    DELETE: 'customer',
    FILTER_INCLUDE_SPENDING: 'customer/filter-include-spending',
  },
  PRODUCT: {
    GETALL: 'product',
    GETONE: 'product',
    CREATE: 'product',
    UPDATE: 'product',
    DELETE: 'product',
  },
  PRODUCTCATEGORY: {
    GETALL: 'productcategory',
  },
  ORDER: {
    GETALL: 'order',
    GETONE: 'order',
    CREATE: 'order',
    UPDATE: 'order',
    DELETE: 'order',
    PAYMENT: 'order/payment',
  },
};
